# Cloudflare Pages configuration
# This file is used for local development and configuration reference
# For actual deployment, use: wrangler pages deploy out

name = "nextchart2"
compatibility_date = "2024-09-25"