// 블록체인 기반 정보
export const blockchainInfo: Record<string, string> = {
  // 첫 번째 파일 데이터
  EUL: "이더리움 (ERC-20)",
  ACS: "솔라나 (SPL)",
  AERGO: "하이브리드 블록체인 (자체 메인넷)",
  AHT: "자체 블록체인",
  AKT: "코스모스 (Cosmos)",
  BFC: "자체 메인넷 (EVM 호환)",
  BORA: "클레이튼 (Klaytn)",
  BOUNTY: "스마트 컨트랙트 플랫폼",
  BRETT: "Base (이더리움 레이어 2)",
  CBK: "이더리움 기반",
  CRO: "크로노스 (Cronos, EVM 호환)",
  CTC: "자체 메인넷 (PoW + PoS)",
  DEEP: "해당 없음 (거래소)",
  DKA: "이더리움 (ERC-20)",
  GRS: "그로스톨코인 (Groestlcoin, 네이티브)",
  HUNT: "이더리움 (ERC-20)",
  MLK: "클레이튼 (Klaytn)",
  MVL: "이더리움 (ERC-20)",
  ORBS: "이더리움 (ERC-20)",
  SNT: "이더리움 (ERC-20)",
  WAVES: "웨이브스 (Waves, 네이티브)",
  AQT: "이더리움",
  BEAM: "자체 블록체인",
  BLAST: "이더리움 (L2)",
  BSV: "비트코인",
  BTT: "트론",
  ELF: "자체 블록체인",
  FCT2: "자체 블록체인",
  GAME2: "자체 블록체인",
  HP: "BNB",
  IP: "자체 블록체인",
  LWA: "수이 (Sui)",
  MED: "자체 블록체인",
  META: "바이낸스 스마트 체인(BSC)",
  MNT: "이더리움 (L2)",
  MOC: "이더리움",
  MOCA: "이더리움",
  NCT: "폴리곤",
  OBSR: "옵저버 (자체 메인넷)",
  PUFFER: "이더리움",
  SKY: "자체 블록체인 (Skycoin)",
  SONIC: "솔라나 (L2)",
  SOON: "이더리움",
  SPURS: "칠리즈 (Chiliz)",
  SWELL: "이더리움",
  TOKAMAK: "이더리움",
  TT: "자체 블록체인",
  USDS: "스텔라",
  UXLINK: "이더리움 (L2)",
  WAL: "이더리움",
  PUMPBTC: "바이낸스 스마트 체인(BSC)",

  // 두 번째 파일 데이터
  MERL: "비트코인 레이어 2 (네이티브)",
  AVNT: "Base",
  AERO: "Base",
  ATH: "솔라나",
  AVAIL: "Avail (네이티브)",
  ai16z: "솔라나 (SPL)",
  AVL: "Avalon Labs 생태계",
  B3: "Base (레이어 3)",
  BLUE: "솔라나",
  CARV: "이더리움 (ERC-20)",
  DRIFT: "솔라나 (SPL)",
  EPT: "이더리움",
  F: "이더리움 (ERC-20)",
  FLOCK: "BNB 체인 (BSC)",
  G: "PlayBlock (네이티브)",
  GOAT: "비트코인 ZK 롤업",
  GRASS: "솔라나 (레이어 2)",
  H: "이더리움 (레이어 2, Polygon CDK)",
  MEW: "솔라나 (SPL)",
  MOODENG: "솔라나 (SPL)",
  OBT: "이더리움",
  ORDER: "NEAR",
  PEFFUR: "이더리움 (ERC-20)",
  PEAQ: "peaq (네이티브, 레이어 1)",
  POKT: "Pocket Network (네이티브, PoS)",
  PROMPT: "AI Wayfinder Ecosystem",
  PROVE: "이더리움 (ERC-20)",
  RESOLV: "Immutable",
  SAFE: "솔라나 포크",
  SD: "이더리움 (ERC-20)",
  SUNDOG: "트론 (TRC)",
  TAIKO: "이더리움 레이어 2 (ZK-Rollup)",
  TOWNS: "이더리움 (ERC-20)",
  XTER: "Xterio (네이티브, PoS)",
  ZETA: "ZetaChain (네이티브, PoS)",
  ZRC: "이더리움 (레이어 2, ZK-Rollup)",

  // 세 번째 파일 데이터
  "1INCH": "이더리움 (ERC-20)",
  AAVE: "이더리움 (ERC-20)",
  ACE: "Endurance (네이티브)",
  ACH: "이더리움 (ERC-20)",
  ACX: "이더리움 (ERC-20)",
  ADA: "카르다노 (네이티브)",
  AGLD: "이더리움 (ERC-20)",
  ALGO: "알고랜드 (네이티브)",
  ALICE: "이더리움 (ERC-20)",
  ALT: "이더리움 (ERC-20)",
  AMP: "이더리움 (ERC-20)",
  ANIME: "이더리움 (ERC-20)",
  ANKR: "이더리움 (ERC-20)",
  APE: "이더리움 (ERC-20)",
  API3: "이더리움 (ERC-20)",
  APT: "앱토스 (네이티브)",
  AR: "아위브 (네이티브)",
  ARB: "이더리움 (ERC-20)",
  ARDR: "아더 (네이티브)",
  ARK: "ARK (네이티브)",
  ARKM: "이더리움 (ERC-20)",
  ARPA: "이더리움 (ERC-20)",
  ASTR: "아스타 (네이티브)",
  ATOM: "코스모스 (네이티브)",
  AUCTION: "이더리움 (ERC-20)",
  AUDIO: "이더리움 (ERC-20)",
  AVAX: "아발란체 (네이티브)",
  AXS: "이더리움 (ERC-20)",
  BAT: "이더리움 (ERC-20)",
  BB: "BounceBit (네이티브)",
  BCH: "비트코인 캐시 (네이티브)",
  BEL: "이더리움 (ERC-20)",
  BERA: "Berachain (네이티브)",
  BICO: "이더리움 (ERC-20)",
  BIGTIME: "이더리움 (ERC-20)",
  BLUR: "이더리움 (ERC-20)",
  BNB: "BNB 체인 (네이티브)",
  BNT: "이더리움 (ERC-20)",
  BONK: "솔라나 (SPL)",
  BTC: "비트코인 (네이티브)",
  C98: "이더리움 (ERC-20)",
  CAKE: "BNB 체인 (BEP-20)",
  CELO: "셀로 (네이티브)",
  CELR: "이더리움 (ERC-20)",
  CFX: "컨플럭스 (네이티브)",
  CHR: "이더리움 (ERC-20)",
  CHZ: "이더리움 (ERC-20)",
  CKB: "너보스 네트워크 (네이티브)",
  COMP: "이더리움 (ERC-20)",
  COOKIE: "이더리움 (ERC-20)",
  COS: "BNB 체인 (BEP-2)",
  COTI: "COTI (네이티브)",
  COW: "이더리움 (ERC-20)",
  CRV: "이더리움 (ERC-20)",
  CTK: "Shentu 체인 (네이티브)",
  CTSI: "이더리움 (ERC-20)",
  CVC: "이더리움 (ERC-20)",
  CYBER: "이더리움 (ERC-20)",
  DOGE: "도지코인 (네이티브)",
  DOT: "폴카닷 (네이티브)",
  DYDX: "이더리움 (ERC-20)",
  EDU: "BNB 체인 (BEP-20)",
  EGLD: "멀티버스엑스 (네이티브)",
  EIGEN: "이더리움 (ERC-20)",
  ENA: "이더리움 (ERC-20)",
  ENJ: "이더리움 (ERC-20)",
  ENS: "이더리움 (ERC-20)",
  ETC: "이더리움 클래식 (네이티브)",
  ETH: "이더리움 (네이티브)",
  ETHFI: "이더리움 (ERC-20)",
  FET: "Fetch.ai (네이티브)",
  FIDA: "솔라나 (SPL)",
  FIL: "파일코인 (네이티브)",
  FLOKI: "이더리움 (ERC-20)",
  FLOW: "플로우 (네이티브)",
  FLUX: "Flux (네이티브)",
  FXS: "이더리움 (ERC-20)",
  GALA: "이더리움 (ERC-20)",
  GAS: "네오 (NEO)",
  GLM: "이더리움 (ERC-20)",
  GMT: "솔라나 (SPL)",
  GMX: "Arbitrum",
  GNO: "이더리움 (ERC-20)",
  GRT: "이더리움 (ERC-20)",
  GTC: "이더리움 (ERC-20)",
  HBAR: "헤데라 (네이티브)",
  HFT: "이더리움 (ERC-20)",
  HIGH: "이더리움 (ERC-20)",
  HIVE: "하이브 (네이티브)",
  HOOK: "BNB 체인 (BEP-20)",
  HUMA: "이더리움 (ERC-20)",
  ICP: "인터넷 컴퓨터 (네이티브)",
  ICX: "아이콘 (네이티브)",
  ID: "이더리움 (ERC-20)",
  ILV: "이더리움 (ERC-20)",
  IMX: "이더리움 (ERC-20)",
  INJ: "인젝티브 (네이티브)",
  IO: "솔라나 (SPL)",
  IOST: "IOST (네이티브)",
  IOTA: "IOTA (네이티브)",
  IOTX: "IoTeX (네이티브)",
  IQ: "이더리움 (ERC-20)",
  JASMY: "이더리움 (ERC-20)",
  JOE: "아발란체 (ARC-20)",
  JST: "트론 (TRC-20)",
  JTO: "솔라나 (SPL)",
  JUP: "솔라나 (SPL)",
  KAIA: "Kaia (네이티브)",
  KAVA: "카바 (네이티브)",
  KNC: "이더리움 (ERC-20)",
  KSM: "쿠사마 (네이티브)",
  LA: "이더리움 (ERC-20)",
  LDO: "이더리움 (ERC-20)",
  LINK: "이더리움 (ERC-20)",
  LISTA: "BNB 체인 (BEP-20)",
  LPT: "이더리움 (ERC-20)",
  LRC: "이더리움 (ERC-20)",
  LSK: "리스크 (네이티브)",
  MAGIC: "이더리움 (ERC-20)",
  MANA: "이더리움 (ERC-20)",
  MANTA: "이더리움 (ERC-20)",
  MASK: "이더리움 (ERC-20)",
  MAV: "이더리움 (ERC-20)",
  MBL: "온톨로지 (OEP-4)",
  METIS: "이더리움 (ERC-20)",
  MINA: "미나 프로토콜 (네이티브)",
  MTL: "이더리움 (ERC-20)",
  NEAR: "니어 프로토콜 (네이티브)",
  NEO: "네오 (네이티브)",
  NMR: "이더리움 (ERC-20)",
  OGN: "이더리움 (ERC-20)",
  OM: "이더리움 (ERC-20)",
  OMNI: "이더리움 (ERC-20)",
  ONDO: "이더리움 (ERC-20)",
  ONG: "온톨로지 (네이티브)",
  ONT: "온톨로지 (네이티브)",
  OP: "이더리움 (ERC-20)",
  ORCA: "솔라나 (SPL)",
  OSMO: "오스모시스 (네이티브)",
  OXT: "이더리움 (ERC-20)",
  PAXG: "이더리움 (ERC-20)",
  PENDLE: "이더리움 (ERC-20)",
  PEPE: "이더리움 (ERC-20)",
  POL: "이더리움 (ERC-20)",
  POLYX: "Polymesh (네이티브)",
  POWR: "이더리움 (ERC-20)",
  PUNDIX: "이더리움 (ERC-20)",
  PYR: "이더리움 (ERC-20)",
  PYTH: "솔라나 (SPL)",
  QKC: "QuarkChain (네이티브)",
  QTUM: "퀀텀 (네이티브)",
  RAD: "이더리움 (ERC-20)",
  RAY: "솔라나 (SPL)",
  REI: "REI Network (네이티브)",
  RENDER: "이더리움 (ERC-20)",
  REQ: "이더리움 (ERC-20)",
  REZ: "이더리움 (ERC-20)",
  RLC: "이더리움 (ERC-20)",
  RPL: "이더리움 (ERC-20)",
  RSR: "이더리움 (ERC-20)",
  RVN: "레이븐코인 (네이티브)",
  SAND: "이더리움 (ERC-20)",
  SC: "시아 (네이티브)",
  SEI: "세이 (네이티브)",
  SFP: "BNB 체인 (BEP-20)",
  SHIB: "이더리움 (ERC-20)",
  SKL: "이더리움 (ERC-20)",
  SNX: "이더리움 (ERC-20)",
  SOL: "솔라나 (네이티브)",
  SOLV: "Arbitrum",
  SOPH: "이더리움 (ERC-20)",
  STEEM: "스팀 (네이티브)",
  STG: "이더리움 (ERC-20)",
  STORJ: "이더리움 (ERC-20)",
  STRAX: "스트라티스 (네이티브)",
  STRK: "이더리움 (ERC-20)",
  STX: "스택스 (네이티브)",
  SUI: "수이 (네이티브)",
  SUN: "트론 (TRC-20)",
  SUSHI: "이더리움 (ERC-20)",
  SXP: "솔라 (네이티브)",
  T: "이더리움 (ERC-20)",
  TFUEL: "쎄타 (네이티브)",
  THETA: "쎄타 (네이티브)",
  TIA: "셀레스티아 (네이티브)",
  TON: "TON (네이티브)",
  TRUMP: "이더리움 (ERC-20)",
  TRX: "트론 (네이티브)",
  TURBO: "이더리움 (ERC-20)",
  UMA: "이더리움 (ERC-20)",
  UNI: "이더리움 (ERC-20)",
  USDC: "이더리움 (ERC-20)",
  USDT: "이더리움 (ERC-20)",
  VANA: "이더리움 (ERC-20)",
  VET: "비체인 (네이티브)",
  VIRTUAL: "이더리움 (ERC-20)",
  VTHO: "비체인 (네이티브)",
  W: "이더리움 (ERC-20)",
  WAXP: "WAX (네이티브)",
  WIF: "솔라나 (SPL)",
  WLD: "이더리움 (ERC-20)",
  WOO: "이더리움 (ERC-20)",
  XAI: "Arbitrum",
  XEC: "이캐시 (네이티브)",
  XLM: "스텔라 (네이티브)",
  XRP: "XRP 레저 (네이티브)",
  XTZ: "테조스 (네이티브)",
  XVS: "BNB 체인 (BEP-20)",
  YFI: "이더리움 (ERC-20)",
  YGG: "이더리움 (ERC-20)",
  ZIL: "질리카 (네이티브)",
  ZK: "이더리움 (ERC-20)",
  ZRO: "이더리움 (ERC-20)",
  ZRX: "이더리움 (ERC-20)",
};

// 코인 설명 정보
export const coinDescriptions: Record<string, string> = {
  EUL: "탈중앙화 금융(DeFi) 렌딩 프로토콜인 오일러 파이낸스(Euler Finance)의 거버넌스 토큰입니다.",
  ACS: "콘텐츠 크리에이터의 구독 모델을 지원하는 액세스 프로토콜(Access Protocol)의 네이티브 토큰입니다.",
  AERGO:
    "기업용 하이브리드 블록체인 플랫폼으로, 퍼블릭과 프라이빗 체인을 함께 지원하며 SQL 기반 스마트 컨트랙트 작성이 가능합니다.",
  AHT: "지식 Q&A 커뮤니티인 '아하'에서 콘텐츠 보상 및 활동에 사용되는 유틸리티 토큰입니다.",
  AKT: "탈중앙화 클라우드 컴퓨팅 네트워크인 아카시 네트워크(Akash Network)에서 컴퓨팅 자원 거래 및 스테이킹에 사용되는 유틸리티 토큰입니다.",
  BFC: "여러 블록체인을 연결하는 멀티체인 미들웨어 플랫폼 바이프로스트(Bifrost)의 네이티브 토큰입니다.",
  BORA: "게임과 디지털 콘텐츠에 특화된 탈중앙화 엔터테인먼트 플랫폼 보라(BORA)의 네이티브 토큰입니다. 초기에는 이더리움 기반이었으나 클레이튼으로 마이그레이션했습니다.",
  BOUNTY:
    "주로 한국 거래소에서 거래되며, 현상금 시스템과 관련된 프로젝트의 토큰으로 보입니다. 솔라나 기반의 다른 'BNTY' 토큰도 존재합니다.",
  BRETT:
    "인터넷 밈 캐릭터에서 영감을 받은 밈 코인으로, 이더리움 레이어 2인 베이스(Base) 블록체인 위에서 작동합니다.",
  CBK: "한국의 암호화폐 커뮤니티 플랫폼인 코박(Cobak)에서 보상 및 프리미엄 서비스 이용에 사용되는 유틸리티 토큰입니다.",
  CRO: "Crypto.com이 개발한 블록체인 크로노스의 네이티브 토큰으로, DeFi, NFT 및 Web3 애플리케이션을 지원합니다.",
  CTC: "국경 없는 신용 투자 네트워크를 목표로 하는 크레딧코인(Creditcoin)의 네이티브 토큰으로, 신용 거래 기록에 사용됩니다.",
  DEEP: "특정 코인이 아닌 암호화폐 거래소 '딥코인(Deepcoin)'을 지칭하는 것으로 보입니다. 거래소 자체 토큰일 수 있으나 블록체인 정보는 제한적입니다.",
  DKA: "블록체인 기반 물류 솔루션 디카르고(dKargo)의 네이티브 유틸리티 토큰으로, 물류 생태계 참여자에게 보상으로 지급됩니다.",
  GRS: "비트코인에서 파생된 암호화폐로, 빠른 속도와 낮은 수수료, 개인 정보 보호에 중점을 둔 자체 블록체인을 가지고 있습니다.",
  HUNT: "다양한 DApp과 게임을 위한 커뮤니티 기반 프로젝트인 헌트(HUNT) 네트워크의 유틸리티 토큰입니다.",
  MLK: "라이프스타일 분야의 여러 서비스 포인트를 통합하고 교환할 수 있는 플랫폼 밀크(MiL.k)의 네이티브 토큰입니다.",
  MVL: "블록체인 기반의 모빌리티 생태계 엠블(MVL)의 유틸리티 토큰으로, 운행 데이터 기록 및 보상에 사용됩니다.",
  ORBS: "대규모 애플리케이션을 위한 하이브리드 블록체인 인프라 오브스(Orbs)의 네이티브 토큰입니다.",
  SNT: "탈중앙화 메시징 앱, 지갑, 웹3 브라우저 기능을 갖춘 스테이터스(Status) 네트워크의 유틸리티 토큰입니다.",
  WAVES:
    "커스텀 토큰 발행과 탈중앙화 애플리케이션(dApp) 개발을 지원하는 자체 블록체인 플랫폼 웨이브스의 네이티브 토큰입니다.",

  // 더 많은 설명들을 추가...
  "1INCH": "탈중앙화 거래소(DEX) 애그리게이터. BNB 체인, 폴리곤 등도 지원.",
  AAVE: "탈중앙화 금융(DeFi) 대출 프로토콜.",
  ACE: "게임 및 소셜 블록체인인 Endurance 메인넷의 네이티브 토큰.",
  ACH: "법정화폐와 암호화폐 결제를 연결하는 Alchemy Pay의 토큰.",
  ACX: "크로스체인 브릿지 프로토콜인 Across Protocol의 토큰.",
  ADA: "지분증명(PoS) 방식의 3세대 블록체인 플랫폼.",
  AGLD: "Loot NFT 프로젝트의 네이티브 토큰.",
  ALGO: "순수 지분증명(PPoS) 합의 메커니즘을 사용하는 블록체인.",
  ALICE: "My Neighbor Alice 게임의 토큰. BNB 체인, 솔라나도 지원.",
  ALT: "롤업을 위한 개방형 프로토콜인 AltLayer의 유틸리티 토큰.",
  AMP: "결제 담보화를 위한 디지털 담보 토큰.",
  ANIME: "애니메이션 팬과 크리에이터를 위한 커뮤니티 토큰.",
  ANKR: "탈중앙화 웹3 인프라 제공업체 Ankr의 토큰.",
  APE: "APE 생태계의 거버넌스 및 유틸리티 토큰.",
  API3: "API와 블록체인을 연결하는 오라클 솔루션.",
  APT: "확장성과 안전성에 중점을 둔 레이어 1 블록체인.",
  AR: "영구 데이터 저장을 목표로 하는 탈중앙화 스토리지 네트워크.",
  ARB: "이더리움 레이어 2 확장 솔루션인 아비트럼의 거버넌스 토큰.",
  ARDR: "부모-자식 체인 구조를 가진 멀티체인 블록체인 플랫폼.",
  ARK: "상호 운용성에 초점을 맞춘 레이어 1 블록체인.",
  ARKM: "블록체인 분석 플랫폼 Arkham Intelligence의 유틸리티 토큰.",
  ARPA: "보안 컴퓨팅 네트워크 ARPA Chain의 토큰.",
  ASTR: "폴카닷의 파라체인으로 작동하는 스마트 컨트랙트 허브.",
  ATOM: "블록체인 간의 상호 운용을 위한 '블록체인의 인터넷'.",
  AUCTION: "탈중앙화 경매 플랫폼 Bounce Finance의 거버넌스 토큰.",
  AUDIO: "탈중앙화 음악 스트리밍 프로토콜 Audius의 토큰.",
  AVAX: "높은 처리량과 빠른 완결성을 제공하는 레이어 1 블록체인.",
  AXS: "블록체인 게임 '엑시 인피니티'의 거버넌스 토큰.",
  BAT: "브레이브 브라우저에서 사용되는 디지털 광고 토큰.",
  BB: "비트코인 리스테이킹을 기반으로 하는 PoS 레이어 1 체인.",
  BCH: "비트코인에서 하드포크된 P2P 전자 현금 시스템.",
  BEL: "DeFi 자산 관리를 위한 Bella Protocol의 토큰.",
  BERA: "DeFi에 최적화된 EVM 호환 레이어 1 블록체인의 가스 토큰.",
  BICO: "웹3 개발을 간소화하는 Biconomy 프로토콜의 토큰.",
  BIGTIME: "PC 액션 RPG 'Big Time'의 게임 내 화폐.",
  BLUR: "NFT 마켓플레이스 Blur의 거버넌스 토큰.",
  BNB: "바이낸스 생태계의 핵심 암호화폐.",
  BNT: "탈중앙화 유동성 프로토콜 Bancor의 네트워크 토큰.",
  BONK: "솔라나 블록체인 기반의 커뮤니티 중심 밈 코인.",
  BTC: "최초의 탈중앙화된 디지털 통화.",
  C98: "DeFi 게이트웨이 Coin98의 유틸리티 및 거버넌스 토큰.",
  CAKE: "탈중앙화 거래소 팬케이크스왑의 거버넌스 토큰.",
  CELO: "모바일 우선의 금융 서비스 및 결제를 위한 블록체인.",
  CELR: "오프체인 확장 솔루션 Celer Network의 유틸리티 토큰.",
  CFX: "높은 처리량을 목표로 하는 PoW 기반 레이어 1 블록체인.",
  CHR: "관계형 블록체인 플랫폼 Chromia의 네이티브 토큰.",
  CHZ: "스포츠 및 엔터테인먼트 팬 토큰 발행 플랫폼 칠리즈의 화폐.",
  CKB: "다중 자산 저장을 지원하는 PoW 기반 레이어 1 블록체인.",
  COMP: "DeFi 대출 프로토콜 Compound의 거버넌스 토큰.",
  COOKIE: "웹3 마케팅 및 분석 플랫폼 Cookie3의 토큰.",
  COS: "탈중앙화 콘텐츠 생태계 Contentos의 토큰.",
  COTI: "DAG 기반의 결제 프로토콜.",
  COW: "CoW Protocol(구 Gnosis Protocol)의 거버넌스 토큰.",
  CRV: "스테이블코인 DEX인 Curve Finance의 거버넌스 토큰.",
  CTK: "보안에 중점을 둔 블록체인 Shentu의 네이티브 토큰.",
  CTSI: "복잡한 연산을 오프체인에서 실행하는 Cartesi의 토큰.",
  CVC: "탈중앙화 신원 확인 솔루션 Civic의 유틸리티 토큰.",
  CYBER: "웹3 소셜 네트워크 CyberConnect의 거버넌스 토큰.",
  DOGE: "밈(meme)에서 시작된 P2P 암호화폐.",
  DOT: "서로 다른 블록체인을 연결하는 멀티체인 네트워크.",
  DYDX: "탈중앙화 파생상품 거래소 dYdX의 거버넌스 토큰.",
  EDU: "탈중앙화 교육 플랫폼 Open Campus의 유틸리티 토큰.",
  EGLD: "높은 확장성을 가진 블록체인 플랫폼(구 엘론드).",
  EIGEN: "이더리움 리스테이킹 프로토콜 EigenLayer의 토큰.",
  ENA: "합성 달러 프로토콜 Ethena Labs의 거버넌스 토큰.",
  ENJ: "NFT 발행 및 게임 아이템 관리를 위한 엔진코인.",
  ENS: "이더리움 주소를 사람이 읽기 쉬운 이름으로 변환하는 ENS의 토큰.",
  ETC: "이더리움의 오리지널 체인.",
  ETH: "스마트 컨트랙트 기능을 갖춘 대표적인 블록체인 플랫폼.",
  ETHFI: "유동성 리스테이킹 프로토콜 Ether.fi의 거버넌스 토큰.",
  FET: "AI 기반 탈중앙화 디지털 경제를 위한 플랫폼.",
  FIDA: "솔라나 기반 DeFi 프로젝트 Bonfida의 토큰.",
  FIL: "탈중앙화 스토리지 네트워크 파일코인의 네이티브 토큰.",
  FLOKI: "커뮤니티 중심의 밈 코인이자 웹3 생태계 토큰.",
  FLOW: "NFT와 대규모 게임에 최적화된 레이어 1 블록체인.",
  FLUX: "탈중앙화 클라우드 인프라 Flux의 네이티브 암호화폐.",
  FXS: "알고리즘 스테이블코인 프로토콜 Frax Finance의 거버넌스 토큰.",
  GALA: "블록체인 게임 플랫폼 갈라 게임즈의 유틸리티 토큰.",
  GAS: "네오 블록체인에서 트랜잭션 수수료로 사용되는 유틸리티 토큰.",
  GLM: "탈중앙화 컴퓨팅 파워 공유 네트워크 Golem의 토큰.",
  GMT: "M2E(Move-to-Earn) 앱 스테픈(STEPN)의 거버넌스 토큰.",
  GMX: "탈중앙화 무기한 선물 거래소 GMX의 유틸리티 및 거버넌스 토큰.",
  GNO: "예측 시장 플랫폼 Gnosis의 토큰.",
  GRT: "블록체인 데이터 인덱싱 프로토콜 The Graph의 토큰.",
  GTC: "오픈소스 프로젝트 펀딩 플랫폼 Gitcoin의 거버넌스 토큰.",
  HBAR: "해시그래프 합의 알고리즘을 사용하는 분산 원장 기술.",
  HFT: "탈중앙화 거래소 Hashflow의 거버넌스 토큰.",
  HIGH: "메타버스 프로젝트 Highstreet의 네이티브 토큰.",
  HIVE: "콘텐츠 제작 및 소셜 활동을 위한 블록체인.",
  HOOK: "웹3 교육 및 온보딩 플랫폼 Hooked Protocol의 토큰.",
  HUMA: "실물 자산(RWA) 대출을 위한 Huma Finance의 토큰.",
  ICP: "웹 속도로 실행되는 탈중앙화 인터넷을 위한 블록체인.",
  ICX: "서로 다른 블록체인을 연결하는 인터체인 프로젝트.",
  ID: "탈중앙화 신원 프로토콜 SPACE ID의 거버넌스 토큰.",
  ILV: "블록체인 게임 '일루비움'의 거버넌스 및 유틸리티 토큰.",
  IMX: "이더리움 기반 NFT를 위한 레이어 2 확장 솔루션.",
  INJ: "DeFi에 최적화된 레이어 1 블록체인.",
  IO: "탈중앙화 AI 컴퓨팅 네트워크 IO.NET의 네이티브 토큰.",
  IOST: "높은 처리량을 목표로 하는 엔터프라이즈급 블록체인.",
  IOTA: "IoT 환경에 최적화된 탱글(Tangle) 기반 분산 원장.",
  IOTX: "IoT 기기를 위한 블록체인 플랫폼.",
  IQ: "블록체인 지식 플랫폼 IQ.wiki의 거버넌스 토큰.",
  JASMY: "개인 데이터 주권을 위한 IoT 플랫폼 Jasmy의 토큰.",
  JOE: "아발란체 기반의 탈중앙화 거래소 Trader Joe의 토큰.",
  JST: "트론 기반의 DeFi 플랫폼 JUST의 거버넌스 토큰.",
  JTO: "솔라나 유동성 스테이킹 프로토콜 Jito의 거버넌스 토큰.",
  JUP: "솔라나 기반 DEX 애그리게이터 Jupiter의 거버넌스 토큰.",
  KAIA: "클레이튼과 핀시아가 통합된 새로운 레이어 1 메인넷.",
  KAVA: "코스모스와 이더리움의 장점을 결합한 레이어 1 블록체인.",
  KNC: "탈중앙화 유동성 프로토콜 카이버 네트워크의 토큰.",
  KSM: "폴카닷의 실험적인 '카나리아' 네트워크.",
  LA: "암호화폐 거래소 LATOKEN의 네이티브 토큰.",
  LDO: "유동성 스테이킹 프로토콜 Lido DAO의 거버넌스 토큰.",
  LINK: "탈중앙화 오라클 네트워크 체인링크의 네이티브 토큰.",
  LISTA: "유동성 스테이킹 및 탈중앙화 스테이블코인 프로토콜.",
  LPT: "탈중앙화 비디오 스트리밍 네트워크 Livepeer의 토큰.",
  LRC: "이더리움 레이어 2 확장 프로토콜 Loopring의 토큰.",
  LSK: "자바스크립트 기반의 블록체인 애플리케이션 플랫폼.",
  MAGIC: "탈중앙화 게임 생태계 Treasure의 네이티브 토큰.",
  MANA: "가상현실 플랫폼 디센트럴랜드의 화폐.",
  MANTA: "영지식 증명을 활용한 모듈러 블록체인.",
  MASK: "소셜 미디어와 웹3를 연결하는 Mask Network의 토큰.",
  MAV: "동적 분배 AMM 기반 DEX Maverick Protocol의 토큰.",
  MBL: "블록체인 기반 영화 및 콘텐츠 플랫폼 무비블록의 토큰.",
  METIS: "이더리움 레이어 2 확장 솔루션 MetisDAO의 토큰.",
  MINA: "22KB의 고정된 크기를 유지하는 경량 블록체인.",
  MTL: "결제 앱 Metal Pay와 관련된 유틸리티 토큰.",
  NEAR: "샤딩 기술을 통해 확장성을 해결하는 레이어 1 블록체인.",
  NEO: "스마트 경제를 위한 블록체인 플랫폼.",
  NMR: "헤지펀드 Numerai의 데이터 과학자들이 사용하는 토큰.",
  OGN: "탈중앙화 마켓플레이스 구축을 위한 Origin Protocol의 토큰.",
  OM: "DeFi 프로토콜 MANTRA DAO의 네이티브 토큰.",
  OMNI: "이더리움의 롤업들을 통합하는 인터체인 네트워크 Omni Network의 토큰.",
  ONDO: "실물 자산(RWA) 토큰화 플랫폼 Ondo Finance의 거버넌스 토큰.",
  ONG: "온톨로지 블록체인의 트랜잭션 수수료로 사용되는 가스 토큰.",
  ONT: "신뢰 기반의 협업을 위한 분산 원장 플랫폼.",
  OP: "이더리움 레이어 2 확장 솔루션 옵티미즘의 거버넌스 토큰.",
  ORCA: "솔라나 기반의 사용자 친화적 탈중앙화 거래소.",
  OSMO: "코스모스 생태계의 인터체인 AMM DEX.",
  OXT: "탈중앙화 VPN 서비스 Orchid Protocol의 유틸리티 토큰.",
  PAXG: "실제 금 1온스에 해당하는 가치를 지닌 디지털 자산.",
  PENDLE: "수익률 토큰화 및 거래를 위한 프로토콜.",
  PEPE: "페페 더 프로그 밈을 기반으로 한 밈 코인.",
  POL: "폴리곤 생태계의 업그레이드된 네이티브 토큰.",
  POLYX: "규제된 자산을 위한 기관 등급 블록체인.",
  POWR: "P2P 에너지 거래 플랫폼 Power Ledger의 토큰.",
  PUNDIX: "블록체인 기반 POS 솔루션 Pundi X의 토큰.",
  PYR: "블록체인 게임 스튜디오 Vulcan Forged의 유틸리티 토큰.",
  PYTH: "실시간 시장 데이터를 블록체인에 제공하는 오라클 네트워크.",
  QKC: "샤딩 기술을 활용한 유연하고 확장 가능한 블록체인.",
  QTUM: "비트코인의 UTXO 모델과 이더리움의 EVM을 결합한 블록체인.",
  RAD: "코드 협업을 위한 P2P 네트워크 Radicle의 거버넌스 토큰.",
  RAY: "솔라나 기반 AMM DEX Raydium의 유틸리티 토큰.",
  REI: "EVM과 호환되는 경량 블록체인 프레임워크.",
  RENDER: "분산형 GPU 렌더링 네트워크 Render Network의 토큰.",
  REQ: "탈중앙화 결제 시스템 Request Network의 유틸리티 토큰.",
  REZ: "유동성 리스테이킹 프로토콜 Renzo의 거버넌스 토큰.",
  RLC: "분산형 클라우드 컴퓨팅 플랫폼 iExec RLC의 토큰.",
  RPL: "탈중앙화 이더리움 스테이킹 프로토콜 Rocket Pool의 토큰.",
  RSR: "스테이블코인 플랫폼 Reserve Protocol의 유틸리티 토큰.",
  RVN: "자산 생성을 전문으로 하는 P2P 블록체인.",
  SAND: "메타버스 플랫폼 '더 샌드박스'의 유틸리티 토큰.",
  SC: "탈중앙화 클라우드 스토리지 플랫폼 시아코인의 화폐.",
  SEI: "거래에 최적화된 범용 오픈소스 레이어 1 블록체인.",
  SFP: "암호화폐 지갑 SafePal의 유틸리티 토큰.",
  SHIB: "도지코인에서 영감을 받은 밈 코인 시바이누.",
  SKL: "이더리움 확장 솔루션 SKALE Network의 유틸리티 토큰.",
  SNX: "탈중앙화 합성 자산 발행 프로토콜 신세틱스의 토큰.",
  SOL: "높은 처리량과 낮은 수수료를 자랑하는 레이어 1 블록체인.",
  SOLV: "유동성 자산 펀드 발행 및 거래를 위한 DeFi 프로토콜.",
  SOPH: "엔터테인먼트 및 게임에 중점을 둔 L2 블록체인 Sophon의 토큰.",
  STEEM: "소셜 미디어 및 콘텐츠 보상을 위한 블록체인.",
  STG: "크로스체인 브릿지 Stargate Finance의 네이티브 토큰.",
  STORJ: "탈중앙화 클라우드 스토리지 네트워크 Storj의 결제 토큰.",
  STRAX: "기업용 블록체인 솔루션 개발 플랫폼.",
  STRK: "이더리움 레이어 2 확장 솔루션 스타크넷의 토큰.",
  STX: "비트코인을 기반으로 스마트 컨트랙트와 앱을 구현하는 레이어.",
  SUI: "낮은 지연 시간과 높은 처리량을 목표로 하는 레이어 1 블록체인.",
  SUN: "트론 기반의 DeFi 플랫폼.",
  SUSHI: "AMM DEX 스시스왑의 거버넌스 토큰.",
  SXP: "암호화폐 결제 및 카드 서비스를 제공하는 Swipe의 토큰.",
  T: "웹3 인프라 프로젝트 Threshold Network의 유틸리티 토큰.",
  TFUEL: "쎄타 블록체인의 가스 토큰으로 비디오 스트리밍에 사용.",
  THETA: "탈중앙화 비디오 스트리밍 네트워크 쎄타의 거버넌스 토큰.",
  TIA: "모듈러 블록체인 네트워크 셀레스티아의 네이티브 토큰.",
  TON: "텔레그램이 개발한 확장성 높은 블록체인 플랫폼.",
  TRUMP: "도널드 트럼프를 테마로 한 밈 코인(Maga).",
  TRX: "탈중앙화된 인터넷 및 콘텐츠 공유 시스템을 위한 블록체인.",
  TURBO: "AI를 이용해 생성된 밈 코인.",
  UMA: "금융 계약 및 합성 자산을 위한 프로토콜.",
  UNI: "대표적인 AMM DEX 유니스왑의 거버넌스 토큰.",
  USDC: "미국 달러와 1:1로 연동되는 대표적인 스테이블코인. 다수 체인 지원.",
  USDT: "미국 달러와 1:1로 연동되는 가장 큰 스테이블코인. 다수 체인 지원.",
  VANA: "사용자 데이터 소유권을 위한 분산 네트워크 Vana의 토큰.",
  VET: "공급망 관리 및 비즈니스 프로세스에 특화된 블록체인.",
  VIRTUAL: "The Virtual 프로젝트의 유틸리티 토큰.",
  VTHO: "비체인 블록체인의 트랜잭션 수수료로 사용되는 가스 토큰.",
  W: "크로스체인 메시징 프로토콜 Wormhole의 거버넌스 토큰.",
  WAXP: "NFT 및 가상 아이템 거래에 최적화된 블록체인.",
  WIF: "모자를 쓴 개 밈을 기반으로 한 밈 코인(dogwifhat).",
  WLD: "홍채 인식을 통해 신원을 증명하는 Worldcoin 프로젝트의 토큰.",
  WOO: "유동성 네트워크 WOO Network의 유틸리티 토큰.",
  XAI: "게임에 특화된 Arbitrum Orbit 기반의 레이어 3 블록체인.",
  XEC: "비트코인 캐시에서 하드포크된 암호화폐.",
  XLM: "국경 간 결제 및 송금을 위한 오픈소스 네트워크.",
  XRP: "국제 결제를 위한 실시간 결제 시스템.",
  XTZ: "자체 수정을 지원하는 스마트 컨트랙트 플랫폼.",
  XVS: "BNB 체인 기반의 대출 및 스테이블코인 프로토콜 Venus의 토큰.",
  YFI: "DeFi 수익률 애그리게이터 yearn.finance의 거버넌스 토큰.",
  YGG: "P2E 게임 길드 Yield Guild Games의 유틸리티 토큰.",
  ZIL: "샤딩 기술을 도입한 높은 처리량의 블록체인 플랫폼.",
  ZK: "이더리움 레이어 2 확장 솔루션 zkSync의 거버넌스 토큰.",
  ZRO: "인터체인 메시징 프로토콜 LayerZero의 네이티브 토큰.",
  ZRX: "P2P 토큰 거래를 위한 0x 프로토콜의 유틸리티 토큰.",
  FLUID:
    "플루이드(Fluid)는 이더리움 기반의 유동성 레이어 프로토콜로, 여러 디파이 프로토콜이 공유하는 단일 유동성 풀을 제공합니다. 이를 통해 자본 효율성을 극대화하고, 자동 한도 조정고도화된 청산 메커니즘으로 안정성을 확보합니다. 현재 렌딩, 볼트, DEX 프로토콜을 핵심으로 시작해 점차 다양한 프로토콜로 확장될 예정입니다. 프로토콜의 모든 업그레이드는 FLUID 토큰 보유자들의 거버넌스 투표를 통해 투명하게 결정됩니다.",
  UDIS: "쿠디스(CUDIS)는 모두를 위한 글로벌 장수 장려 프로토콜입니다. 실제 사람 데이터를 통해 구동되며, 쿠디스링이라는 반지형태의 디바이스(스마트링)와 블록체인 기반 모바일앱을 통해, 사용자는 헬스 데이터에 대한 자기 주권을 지니며, 실시간으로 장수 관련 인사이트와 더불어 데이터 제공으로 경제적인 보상을 받을 수 있습니다.",
  MIRA: "미라(Mira)는 AI가 생성한 결과물의 신뢰성 문제를 해결하기 위한 프로젝트입니다. 현재 AI 시스템은 환각(Hallucination)과 편향(Bias)으로 인해 오류가 발생하며, 이는 AI의 광범위한 활용을 제약합니다. 단일 AI 모델로는 이러한 문제를 해결하기 어렵기 때문에, 미라 네트워크는 여러 AI 모델의 집단 지성을 활용하여 분산된 합의 방식으로 AI 결과물을 검증합니다.",
};

// 블록체인 기반으로 마커 생성
export function getBlockchainMarker(symbol: string): string | null {
  const blockchain = blockchainInfo[symbol];
  if (!blockchain) return null;

  // 주요 블록체인별 마커 매핑
  if (blockchain.includes("이더리움") || blockchain.includes("ERC-20"))
    return "ETH";
  if (blockchain.includes("솔라나") || blockchain.includes("SPL")) return "SOL";
  if (
    blockchain.includes("BNB") ||
    blockchain.includes("BSC") ||
    blockchain.includes("BEP-20")
  )
    return "BNB";
  if (blockchain.includes("비트코인") || blockchain.includes("Bitcoin"))
    return "BTC";
  if (blockchain.includes("트론") || blockchain.includes("TRC")) return "TRX";
  if (blockchain.includes("폴리곤") || blockchain.includes("Polygon"))
    return "MATIC";
  if (blockchain.includes("아발란체") || blockchain.includes("Avalanche"))
    return "AVAX";
  if (blockchain.includes("코스모스") || blockchain.includes("Cosmos"))
    return "ATOM";
  if (blockchain.includes("클레이튼") || blockchain.includes("Klaytn"))
    return "KLAY";
  if (blockchain.includes("Base")) return "BASE";
  if (blockchain.includes("Arbitrum")) return "ARB";
  if (blockchain.includes("네이티브") || blockchain.includes("자체"))
    return "NATIVE";
  if (blockchain.includes("레이어 2") || blockchain.includes("L2")) return "L2";

  return "OTHER";
}

// 블록체인 마커 색상
export function getBlockchainMarkerColor(marker: string): string {
  const colors: Record<string, string> = {
    ETH: "bg-blue-50 text-blue-700 border-blue-200 hover:bg-blue-100",
    SOL: "bg-purple-50 text-purple-700 border-purple-200 hover:bg-purple-100",
    BNB: "bg-yellow-50 text-yellow-700 border-yellow-200 hover:bg-yellow-100",
    BTC: "bg-orange-50 text-orange-700 border-orange-200 hover:bg-orange-100",
    TRX: "bg-red-50 text-red-700 border-red-200 hover:bg-red-100",
    MATIC: "bg-indigo-50 text-indigo-700 border-indigo-200 hover:bg-indigo-100",
    AVAX: "bg-red-50 text-red-700 border-red-200 hover:bg-red-100",
    ATOM: "bg-gray-50 text-gray-700 border-gray-200 hover:bg-gray-100",
    KLAY: "bg-pink-50 text-pink-700 border-pink-200 hover:bg-pink-100",
    BASE: "bg-cyan-50 text-cyan-700 border-cyan-200 hover:bg-cyan-100",
    ARB: "bg-blue-50 text-blue-700 border-blue-200 hover:bg-blue-100",
    NATIVE: "bg-green-50 text-green-700 border-green-200 hover:bg-green-100",
    L2: "bg-violet-50 text-violet-700 border-violet-200 hover:bg-violet-100",
    OTHER: "bg-slate-50 text-slate-700 border-slate-200 hover:bg-slate-100",
  };
  return colors[marker] || colors["OTHER"];
}
